# Generated by Django 2.2 on 2020-04-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieName', models.CharField(max_length=64)),
                ('Timing', models.DateField()),
                ('Location', models.CharField(max_length=64)),
            ],
        ),
    ]
